---
- name: Install docker
  shell: "curl -fsSL get.docker.com -o get-docker.sh && sh get-docker.sh"
  become: yes

- name: Add ansible to docker group
  user:
    name: '{{ ansible_user }}'
    groups: docker
    append: yes
  become: yes

- name: Ensure group "docker" exists
  group:
    name: docker
    state: present

- name: Activate group
  shell: "newgrp docker"